### ISSUE TITLE
CDN hosted version not working

### ISSUE THREAD

**Issue by vanam** [stoplightio/spectral-owasp-ruleset#14]
## Current Behavior
If my `.spectral.yml` looks like 
```yml
extends: ["https://unpkg.com/@stoplight/spectral-owasp-ruleset"]
```
as you write in your documentation I get following error.

```
$ spectral lint .spectral.yml https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml --verbose
Error running Spectral!
Error #1: Invalid ruleset provided
          at assertRuleset         …idation/index.js:14  throw new Error('In…
          at read                  …or/dist/index.js:20  (0, validation_1.as…
          at processTicksAndReje…  …cess/task_queues:96
          at async processExtend   …rmers/extends.js:22  return await (0, __…
          at                       …rmers/extends.js:40

```
The same happens if I use your [Docker image](https://hub.docker.com/r/stoplight/spectral).

If I install `@stoplight/spectral-owasp-ruleset` package and my `.spectral.yml` looks like
```yml
extends: ["@stoplight/spectral-owasp-ruleset"]
```
it works as expected.

## Environment

- Version used: 6.5.1
- Environment name and version (e.g. Chrome 39, node.js 5.4): Node.js v16.13.2
- Operating System and version (desktop or mobile): Windows 10

**Comment by vanam** [comment]
@philsturgeon Thanks for a README update. There is no 1.3.1 version for [@stoplight/spectral-owasp-ruleset](https://www.npmjs.com/package/@stoplight/spectral-owasp-ruleset), though.

Example should be
```bash
echo 'extends: ["https://unpkg.com/@stoplight/spectral-owasp-ruleset@1.1.1/dist/ruleset.js"]' > .spectral.yaml
```
instead.

**Comment by philsturgeon** [comment]
Thanks, copy and paste mistake. Fixed that.

**Comment by Eddoson** [comment]
Hello, I'm having this same issue except I can't get either of the suggest .spectral.yaml extends lines to work.
`>echo 'extends: ["https://unpkg.com/@stoplight/spectral-owasp-ruleset@1.1.1/dist/ruleset.js"]' > .spectral.yaml`
I loaded the suggested CDN from the readme
`>spectral lint .\openapi.yaml`
`Error running Spectral!
Use --verbose flag to print the error stack.
Error #1: Invalid ruleset provided`
Now attempting to use the npm version
`>echo 'extends: ["@stoplight/spectral-owasp-ruleset"]' > .spectral.yaml`
`>spectral lint .\openapi.yaml`
`Error running Spectral!
Use --verbose flag to print the error stack.
Error #1: Invalid ruleset provided`
The NPM ruleset also failed

Let me know if you want any more information. Perhaps I missed something?

**Comment by vanam** [comment]
@Eddoson My guess is you have a `.spectral.yml` file with some invalid content (yml might have a priority over yaml file).

Try
```bash
spectral lint .spectral.yaml .\openapi.yaml
```
to make sure you use right file.

But I might be completely wrong.

**Comment by Eddoson** [comment]
@vanam You fixed it! Thank you very much. I deleted the .spectral.yaml entirely and created a brand new file and pasted in the extends code rather than using `echo` then it worked.

**Comment by emi-emi671** [comment]
I am also having the same problem but a different error. I added the 
` echo 'extends: ["https://unpkg.com/@stoplight/spectral-owasp-ruleset@1.1.1/dist/ruleset.js"]' > .spectral.yaml`
and when trying to lint the file:
`spectral lint .spectral.yaml api.yaml `
getting the error:
`Provided ruleset is not an object`


Any clue of that?
