### ISSUE TITLE
Publish .yaml version

### ISSUE THREAD

**Issue by ioggstream** [stoplightio/spectral-owasp-ruleset#15]
## User Story Description
As a USER,

I want to reference a YAML ruleset,

so I can test a specification without installing a package or executing a js file.

## Acceptance Criteria

- [ ] a YAML version of the ruleset is published

## Sprint Ready Checklist

- [ ] Acceptance criteria defined
- [ ] Team understands acceptance criteria
- [ ] Team has defined solution / steps to satisfy acceptance criteria
- [ ] Acceptance criteria is verifiable / testable
- [ ] External / 3rd Party dependencies identified

**Comment by mnaumanali94** [comment]
Hey @ioggstream 

You can export a `json` version from here: https://apistylebook.stoplight.io/docs/owasp-top-10

Does that work?

**Comment by philsturgeon** [comment]
@ioggstream can you expand on the use-case explaining why that is required? Spectral will support loading a .js in a .yaml so the example in the README will work just fine in most scenarios:

```yaml
extends: ["https://unpkg.com/@stoplight/spectral-owasp-ruleset@1.1.1/dist/ruleset.js"]
```

**Comment by philsturgeon** [comment]
I'll close this for now as I think the use case is covered with a CDN. There was an issue that would have meant this didn't work in earlier versions of spectral, but if you update to latest I believe this works just fine from a .yaml file.
