### ISSUE TITLE
Schema/Property can be named type. That causes an error

### ISSUE THREAD

**Issue by mnaumanali94** [stoplightio/spectral-owasp-ruleset#19]
```
{
    name: "valid case: oas3.1",
    document: {
      openapi: "3.1.0",
      info: { version: "1.0" },
      components: {
        schemas: {
          type: {
            type: "string",
            maxLength: 99,
          },
        },
      },
    },
    errors: [],
  },
 ```
 
 This case fails with an error. It shouldn't

**Comment by philsturgeon** [comment]
@mnaumanali94 thanks for reporting this. Can you mention the rule thats failing when you report an issue because sometimes its immediately clear from context and sometimes I stare at it for 5 minutes trying to guess. This one isn't so bad. :D

**Comment by philsturgeon** [comment]
Wait no which rule is this.
