### ISSUE TITLE
Unable to use this ruleset int existing ruleset

### ISSUE THREAD

**Issue by emi-emi671** [stoplightio/spectral-owasp-ruleset#31]
I am trying to extend the owasp rulesets into my custom ruleset file, before that I installed the package on my machine:
`npm install --save -D @stoplight/spectral-owasp-ruleset
npm install --save -D @stoplight/spectral-cli`

my custom ruleset file is like this:

my-ruleset.yaml
`extends: ["@stoplight/spectral-owasp-ruleset"]`

but it seems to be not working when I run the linting command on console:
`spectral lint petstore-openapi.yaml --ruleset=my-ruleset.yaml `

and getting the following output:

Could not parse https://unpkg.com/@stoplight/spectral@5.3.0-owasp-ruleset: Not Found

**Comment by emi-emi671** [comment]
edit text

**Comment by esatterwhite** [comment]
I have the same problem. unable to use this pack in `extends`. I tried multiple styles and yaml formats for arrays and string. 

I also tried using the javascript spectral file format and got the same error

**Comment by esatterwhite** [comment]
@philsturgeon @ksoviero-stoplight any insight here?
The current package seem to be not usable.

**Comment by emi-emi671** [comment]
Hi, I have resolved this by updating spectral CLI to the latest version, and all these problems have been resolved.

**Comment by esatterwhite** [comment]
I'm using the latest version, and I still have this problem

**Comment by emi-emi671** [comment]
Can you try like this:
`extends: "spectral:oas"
rules:`

**Comment by esatterwhite** [comment]
```json5
// package.json
{
  devDependencies: {
  "@apisyouwonthate/style-guide": "^1.4.0",
  "@stoplight/spectral-cli": "^6.6.0",
  "@stoplight/spectral-core": "^1.16.1",
  "@stoplight/spectral-functions": "^1.7.2",
  "@stoplight/spectral-owasp-ruleset": "^1.4.0",
  "@stoplight/spectral-rulesets": "^1.15.0",
  "@stoplight/types": "^13.9.1",
  }
}
```

```yaml
#spectral.yaml
extends: ["@stoplight/spectral-owasp-ruleset"]
```


```shell
spectral lint doc/api.json "--verbose"

Found 25 rules (25 enabled)
Linting /home/esatterwhite/dev/js/logdna/auth-provider-service/doc/api.json
Error running Spectral!
Error #1: Cannot read properties of null (reading 'type')
          at type=="oauth2")]  …js/core/index.js:66  _rollupPluginBabelH…
          at eval              …js/core/index.js:66  _rollupPluginBabelH…
          at _traverseBody     …time/traverse.js:13  cb(scope);          
          at _traverse         …time/traverse.js:41  _traverseBody(key, …
          at _traverseBody     …time/traverse.js:17  _traverse(value, sc…
```

**Comment by esatterwhite** [comment]
> Can you try like this: `extends: "spectral:oas"`

Yes, this works. Its just the owasp package that breaks

**Comment by emi-emi671** [comment]
I have just tried with that and it is working fine for me:

```
#extends: "spectral:oas"
extends: ["@stoplight/spectral-owasp-ruleset"]
rules:
```
and then just download the petstore.yaml file and lint with following command:

`spectral lint petstore.yaml --ruleset=rules.yaml`

I can see the results:
```

petstore.yaml
   2:6         error  info-description                                 OpenAPI object info `description` must be present and at least 20 chars long to describe the API                                                        info
  8:10         error  owasp:api7:2019-security-hosts-https-oas3        Server URLs MUST begin https://, and no other protocol is permitted.                                                                                    servers[0].url
  11:9   information  owasp:api2:2019-protection-global-safe           This operation is not protected by any security scheme.                                                                                                 paths./pets.get
  21:18        error  owasp:api4:2019-integer-limit-legacy             Schema of type integer must specify minimum and maximum.                                                                                                paths./pets.get.parameters[0].schema
  25:17      warning  owasp:api3:2019-define-error-responses-401       Operation is missing responses[401].                                                                                                                    paths./pets.get.responses
  25:17      warning  owasp:api3:2019-define-error-responses-401       Operation is missing responses[401].content.                                                                                                            paths./pets.get.responses
  25:17      warning  owasp:api3:2019-define-error-responses-500       Operation is missing responses[500].                                                                                                                    paths./pets.get.responses
  25:17      warning  owasp:api3:2019-define-error-responses-500       Operation is missing responses[500].content.               
```

**Comment by esatterwhite** [comment]
yes. 6.6.0

**Comment by esatterwhite** [comment]
There is a bug in here

```shell
Cannot read properties of null (reading 'type')
```

I have a valid schema according to every other validator I can find.

**Comment by emi-emi671** [comment]
Did you try to install `npm install --save -D @stoplight/spectral-owasp-ruleset ` in the same directory where your custom ruleset and openAPI spec file are and then see if it works or not?
I did many experiments and then finally I realize that my spectral-cli was old, after upgrading this package stats worked on my system. I just install both the spectral-cli and this package on a new machine and test the lining and it works. There is no other secret.

**Comment by esatterwhite** [comment]
```javascript
!!require('@stoplight/spectral-owasp-ruleset')
true
```

its installed

**Comment by esatterwhite** [comment]
```javascript
console.log(require('@stoplight/spectral-cli/package.json').version)
'6.6.0'
```

**Comment by esatterwhite** [comment]
If I turn the rule `owasp:api2:2019-jwt-best-practices` off, it works.

**Comment by esatterwhite** [comment]
Even if I copy the `authSchemes` out of the standard petstore schema and copy it into my schema, which is a valid schema - I still get this error. So something isn't quite right with this rule
