### ISSUE TITLE
OWASP Ruleset validation is not working in VSCode extension

### ISSUE THREAD

**Issue by shuknk8s** [stoplightio/spectral-owasp-ruleset#33]
Followed the VSCode specific instructions to validate API Spec against OWASP Ruleset @  https://github.com/stoplightio/spectral-owasp-ruleset

Specifically included the following in .spectral.yaml located in the same folder where the API Spec resides

echo 'extends: ["https://unpkg.com/@stoplight/spectral-owasp-ruleset@1.1.1/dist/ruleset.js"]' > .spectral.yaml

Despite that when I opened the Open API Spec , vscode errors out showing nothing in the output tab but complaining about failing to validate the API Spec which was successfully validated by the in built ruleset and other custom rule set but fails in VsCode when the OWSAP Rule set is included. It is working as expected in the via CLI though

Error: 
Spectral: An error occurred while validating /Users/<user id>/Shuvo/owasp-spectral-linting/api/<Open-API-Spec>.json. Please see the 'Spectral' output channel for details.

OS: MacOS 12.6.2
VSCode: 1.76.0
Node: 18.13.0
npm: 9.3.1
Spectral VSCode Plugin: v1.1.0

After enabling tracer, below is the detailed error log 

Using ruleset file: /Users/shuc/api-linting-spectral/.spectral.yaml.
[Error - 8:31:33 PM] An error occurred while validating document /Users/shuc/api-linting-spectral/petstore-api.json: Unable to read ruleset at /Users/shuc/api-linting-spectral/.spectral.yaml. Error: Could not load https://unpkg.com/@stoplight/spectral-owasp-ruleset@1.1.1/dist/%00commonjsHelpers.js (imported by https://unpkg.com/@stoplight/spectral-owasp-ruleset@1.1.1/dist/ruleset.js): Error fetching https://unpkg.com/@stoplight/spectral-owasp-ruleset@1.1.1/dist/%00commonjsHelpers.js: Bad Request
seenDependencies (before): 0.
-----
Scan triggered file file:///Users/shuc/api-linting-spectral/petstore-api.json.
Linting root file file:///Users/shuc/api-linting-spectral/petstore-api.json.
[DBG] lintDocumentOrRoot. knownDeps=[]
pdps: [
  {
    "uri": "file:///Users/shuc/api-linting-spectral/petstore-api.json",
    "diagnostics": []
  }
].
deps: [].
seenDependencies (after): 0.
-----

**Comment by shuknk8s** [comment]
Tested with another custom rule set but figured out vscode extsnsion is completely ignoring the custom rule set specified in the .spectral.yaml file but validating against the in built ruleset which is  contrary to cli behavior  , cli is working exactly as expected against in built and custom ruleset , am I missing any configuration vscode extension?

**Comment by shuknk8s** [comment]
who do I need to reach out to get some traction on this issue?

**Comment by shuknk8s** [comment]
It has been more than 3 weeks since the issue had been reported but yet to receive any response.

**Comment by P0lip** [comment]
@shuknk8s apologies for the delayed response.
I created a PR https://github.com/stoplightio/spectral-owasp-ruleset/pull/39 which should address the issue with vscode extension.

**Comment by P0lip** [comment]
The issue should be resolved now.
Let me know in case you still experience some issues.
Once again my sincere apologies for dropping a ball on this  one.
