### ISSUE TITLE
owasp:api2:2019-no-api-keys-in-url rule is not correctly displayed in API Stylebook

### ISSUE THREAD

**Issue by Filip1x9** [stoplightio/spectral-owasp-ruleset#48]
The name of the rule (i.e. `owasp:api2:2019-no-api-keys-in-url`) is incorrectly written in the [API Stylebook](https://apistylebook.stoplight.io/docs/owasp-top-10). It is written as `api2:2019-no-api-keys-in-url` instead of `owasp:api2:2019-no-api-keys-in-url`

## Context
The change is meant to display the correct name/code of the rule.

## Current Behavior
Currently, I am not able to automatically link the docs for this rule in my API linter any issue with the `owasp:api2:2019-no-api-keys-in-url` due to the incorrect rule name in the documentation

## Expected Behavior
This link should point to the correct rule docs: https://apistylebook.stoplight.io/docs/owasp-top-10/#owasp:api2:2019-no-api-keys-in-url.

## Possible Solution(s)
Change the name in the docs with the proper rule code.

**Comment by Filip1x9** [comment]
Is there any update on this?

**Comment by mnaumanali94** [comment]
This has been fixed!
