### ISSUE TITLE
API7:2023 - Check for redirect URLs

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/spectral-owasp-ruleset#55]
Trying to tackle this bit of API7:

> Blindly follows redirections; this can be used to redirect the client to a malicious website.

The problem is how do we know if an API is blindly following a URL.

Say the OpenAPI allows `GET /login?redirect=https://example.com/whatever`, is this a security issue? 

If they have implemented a whitelist of allowed servers then that may well be ok, because trying to redirect to `GET /login?redirect=https://malicious.com/whatever` is not going to work.

We could make a warning, saying make sure you've got a whitelist on this query string parameter because it appears to be taking a full URL, either change it to a path or silence it with an override?

Check for:

- callback
- callbackUrl
- redirectUri
- redirect

**Comment by mnaumanali94** [comment]
I think we could leverage info/message for these cases at the least where we say "Make sure to review this URL as this could be a security issue" 🤔

**Comment by philsturgeon** [comment]
How's this looking e7450f5 

I went with quick and easy, looking purely at the name, as it seemed like that would more likely cover the bases instead of messing around checking for `format: url` which would likely just get people taking that out and making docs worse. 😓 

Lmk if this is enough.
