### ISSUE TITLE
No matching version found for @stoplight/spectral-owasp-ruleset@2.0

### ISSUE THREAD

**Issue by StefanLecho** [stoplightio/spectral-owasp-ruleset#57]
I'm following the instructions on https://github.com/stoplightio/spectral-owasp-ruleset, but when running "npm install --save -D @stoplight/spectral-owasp-ruleset@^2.0", I'm getting this error: "No matching version found for @stoplight/spectral-owasp-ruleset@2.0"

When running "npm install --save -D @stoplight/spectral-owasp-ruleset@^1.4.3", it works fine. 

Has v2.0 not yet been released ?

**Comment by philsturgeon** [comment]
Sorry, semantic release is bugging out, I'm trying to figure out why and get a proper version out now.

**Comment by philsturgeon** [comment]
It's been released now, but I'm getting errors trying to use it. 

```
spectral lint openapi.yaml --verbose
Found 84 rules (73 enabled)
Linting /Users/phil/src/bump/train-travel-api/openapi.yaml
Error running Spectral!
Error #1: scope.sandbox.value.match is not a function
          at match(/(_url|Url|-u…  …js/core/index.js:66  _rollupPluginBabelH…
          at eval                  …js/core/index.js:66  _rollupPluginBabelH…
          at _traverseBody         …time/traverse.js:13  cb(scope);
          at _traverse             …time/traverse.js:41  _traverseBody(key, …
          at _traverseBody         …time/traverse.js:17  _traverse(value, sc…
```

@mnaumanali94 can you see if one of the team has a clue whats going on there? I can't figure it out from this error message alone.

**Comment by philsturgeon** [comment]
@StefanLecho can you upgrade, are you also getting this?

**Comment by davidkeaveny** [comment]
I'm getting the `scope.sandbox.value.match is not a function` error too:

* Node - 18.16.0
* spectral-cli - 6.11.0
* spectral-owasp-ruleset - 2.0

Downgrading from 2.0.0 to 1.4.3 fixes things.

**Comment by StefanLecho** [comment]
> @StefanLecho can you upgrade, are you also getting this?

After upgrading, I'm able to run v2.0 without any issues.

**Comment by philsturgeon** [comment]
2.0.1 resolved this error. You can close the issue.
