### ISSUE TITLE
401 response required on all operations

### ISSUE THREAD

**Issue by savage-alex** [stoplightio/spectral-owasp-ruleset#9]
## User Story
As an API Designer
I want to be informed if my definition is missing a 401 response
So that my consumers know they will receive a 401 if they fail to authenticate

## Acceptance Criteria
For all operations on all paths
An HTTP 401 response is defined

## Sprint Ready Checklist

- [ ] Acceptance criteria defined
- [ ] Team understands acceptance criteria
- [ ] Team has defined solution / steps to satisfy acceptance criteria
- [ ] Acceptance criteria is verifiable / testable
- [ ] External / 3rd Party dependencies identified

**Comment by philsturgeon** [comment]
Closed by b49caf3.
